name: "Admissibility Witness"
description: "Run admit ci and emit witnessed CI summary."

inputs:
  mode:
    description: "CI mode: observe|audit|enforce"
    required: false
    default: "observe"
  config-path:
    description: "Optional path to .admit/config.toml"
    required: false
    default: ""
  require-github:
    description: "Require github.ceremony scope availability"
    required: false
    default: "false"
  plan-path:
    description: "Optional plan artifact path"
    required: false
    default: "out/plan/plan-artifact.json"
  manifest-path:
    description: "Optional proposal manifest path"
    required: false
    default: "out/plan/proposal-manifest.json"
  plan-rollout:
    description: "Plan contract rollout: advisory|enforce"
    required: false
    default: "advisory"
  comment:
    description: "Post PR comment via gh when possible"
    required: false
    default: "false"

outputs:
  verdict:
    description: "Witness verdict"
    value: ${{ steps.parse.outputs.verdict }}
  witness-hash:
    description: "Witness canonical hash"
    value: ${{ steps.parse.outputs.witness_hash }}
  witness-path:
    description: "Witness artifact path"
    value: ${{ steps.parse.outputs.witness_path }}
  requires-manual-approval:
    description: "Whether plan contract requires manual approval"
    value: ${{ steps.parse.outputs.requires_manual_approval }}
  plan-valid:
    description: "Whether plan artifact validated successfully"
    value: ${{ steps.parse.outputs.plan_valid }}

runs:
  using: "composite"
  steps:
    - name: Build admit CLI
      shell: bash
      run: cargo build -p admit_cli --release

    - name: Run admissibility witness
      id: run_witness
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}
        GH_PR_NUMBER: ${{ github.event.pull_request.number }}
        GH_REPO: ${{ github.repository }}
      run: |
        mkdir -p out/artifacts
        CONFIG_ARG=""
        if [ -n "${{ inputs.config-path }}" ]; then
          CONFIG_ARG="--config ${{ inputs.config-path }}"
        fi
        REQUIRE_GH_ARG=""
        if [ "${{ inputs.require-github }}" = "true" ]; then
          REQUIRE_GH_ARG="--require-github"
        fi
        target/release/admit_cli ci --root . --mode "${{ inputs.mode }}" --json --artifacts-dir out/artifacts --plan "${{ inputs.plan-path }}" --manifest "${{ inputs.manifest-path }}" --plan-rollout "${{ inputs.plan-rollout }}" $CONFIG_ARG $REQUIRE_GH_ARG > out/ci-witness.json

    - name: Parse outputs
      id: parse
      shell: bash
      run: |
        VERDICT=$(jq -r '.verdict // ""' out/ci-witness.json)
        WITNESS_HASH=$(jq -r '.witness_hash // ""' out/ci-witness.json)
        WITNESS_PATH=$(jq -r '.witness_artifact_path // ""' out/ci-witness.json)
        REQUIRES_MANUAL_APPROVAL=$(jq -r '.requires_manual_approval // false' out/ci-witness.json)
        PLAN_VALID=$(jq -r '.plan_contract.plan_valid // false' out/ci-witness.json)
        echo "verdict=$VERDICT" >> "$GITHUB_OUTPUT"
        echo "witness_hash=$WITNESS_HASH" >> "$GITHUB_OUTPUT"
        echo "witness_path=$WITNESS_PATH" >> "$GITHUB_OUTPUT"
        echo "requires_manual_approval=$REQUIRES_MANUAL_APPROVAL" >> "$GITHUB_OUTPUT"
        echo "plan_valid=$PLAN_VALID" >> "$GITHUB_OUTPUT"

    - name: Publish summary
      shell: bash
      run: |
        echo "## Admissibility Witness" >> "$GITHUB_STEP_SUMMARY"
        echo '```json' >> "$GITHUB_STEP_SUMMARY"
        jq . out/ci-witness.json >> "$GITHUB_STEP_SUMMARY" || cat out/ci-witness.json >> "$GITHUB_STEP_SUMMARY"
        echo '```' >> "$GITHUB_STEP_SUMMARY"

    - name: Build PR comment body
      if: ${{ inputs.comment == 'true' }}
      shell: bash
      run: |
        VERDICT=$(jq -r '.verdict // "unknown"' out/ci-witness.json)
        MODE=$(jq -r '.mode // "unknown"' out/ci-witness.json)
        FAIL_THRESHOLD=$(jq -r '.fail_threshold // "unknown"' out/ci-witness.json)
        WITNESS_HASH=$(jq -r '.witness_hash // ""' out/ci-witness.json)
        WITNESS_PATH=$(jq -r '.witness_artifact_path // ""' out/ci-witness.json)
        INTEGRITY_COUNT=$(jq -r '(.integrity_failures // []) | length' out/ci-witness.json)
        SCOPE_WARNING_COUNT=$(jq -r '(.scope_warnings // []) | length' out/ci-witness.json)
        PLAN_VALID=$(jq -r '.plan_contract.plan_valid // false' out/ci-witness.json)
        MANIFEST_VALID=$(jq -r '.plan_contract.manifest_valid // false' out/ci-witness.json)
        MANUAL_APPROVAL=$(jq -r '.requires_manual_approval // false' out/ci-witness.json)
        STOP_REASON_COUNT=$(jq -r '(.stop_reasons // []) | length' out/ci-witness.json)

        cat > out/ci-witness-comment.md <<EOF
        <!-- admit-ci-witness -->
        ## Admissibility Witness

        | key | value |
        | --- | --- |
        | mode | \`$MODE\` |
        | verdict | \`$VERDICT\` |
        | fail_threshold | \`$FAIL_THRESHOLD\` |
        | witness_hash | \`$WITNESS_HASH\` |
        | witness_artifact_path | \`$WITNESS_PATH\` |
        | integrity_failures | \`$INTEGRITY_COUNT\` |
        | scope_warnings | \`$SCOPE_WARNING_COUNT\` |
        | plan_valid | \`$PLAN_VALID\` |
        | manifest_valid | \`$MANIFEST_VALID\` |
        | requires_manual_approval | \`$MANUAL_APPROVAL\` |
        | stop_reasons | \`$STOP_REASON_COUNT\` |

        <details>
        <summary>Full Witness Summary (JSON)</summary>

        \`\`\`json
        $(jq . out/ci-witness.json)
        \`\`\`
        </details>
        EOF

    - name: Best-effort PR comment
      if: ${{ inputs.comment == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        PR_NUMBER="${{ github.event.pull_request.number }}"
        if [ -n "$PR_NUMBER" ]; then
          REPO="${{ github.repository }}"
          MARKER="<!-- admit-ci-witness -->"
          EXISTING_ID=$(gh api "repos/$REPO/issues/$PR_NUMBER/comments" --paginate --jq ".[] | select(.user.login == \"github-actions[bot]\" and (.body | contains(\"$MARKER\"))) | .id" | tail -n 1)

          if [ -n "$EXISTING_ID" ]; then
            gh api --method PATCH "repos/$REPO/issues/comments/$EXISTING_ID" -f body="$(cat out/ci-witness-comment.md)" || true
          else
            gh api --method POST "repos/$REPO/issues/$PR_NUMBER/comments" -f body="$(cat out/ci-witness-comment.md)" || true
          fi
        fi
