mod bool_expr;
mod boundary;
pub mod cbor;
mod constraints;
mod displacement;
mod env;
mod error;
mod eval;
pub mod hash_operations;
pub mod hash_witness;
mod ir;
mod lint;
pub mod plan;
mod provider;
mod predicates;
mod span;
mod symbols;
mod trace;
pub mod witness;

#[cfg(test)]
mod tests;

pub use bool_expr::*;
pub use boundary::{boundary_loss_diff, boundary_loss_diff_name};
pub use cbor::{encode_canonical, encode_canonical_value};
pub use constraints::evaluate_constraints;
pub use displacement::build_displacement_trace;
pub use env::Env;
pub use error::EvalError;
pub use eval::{eval, EvalOpts, FloatPolicy};
pub use hash_operations::*;
pub use hash_witness::*;
pub use ir::*;
pub use lint::LintFinding;
pub use provider::PredicateProvider;
pub use predicates::eval_pred;
pub use span::Span;
pub use symbols::*;
pub use trace::Trace;
pub use witness::*;
pub use plan::*;
